from alpha_tracker2.core.registry import REGISTRY
from alpha_tracker2.ingestion.plugins.mock_provider import MockUniverseProvider
from alpha_tracker2.ingestion.plugins.mock_price_provider import MockPriceProvider

from alpha_tracker2.ingestion.plugins.akshare_provider import AkShareUniverseProvider
REGISTRY.universe_providers[AkShareUniverseProvider.name] = AkShareUniverseProvider
REGISTRY.universe_providers[MockUniverseProvider.name] = MockUniverseProvider

REGISTRY.prices_providers[MockPriceProvider.name] = MockPriceProvider
from alpha_tracker2.ingestion.plugins.akshare_price_provider import AkSharePriceProvider
REGISTRY.prices_providers[AkSharePriceProvider.name] = AkSharePriceProvider
